// Generated by CoffeeScript 1.4.0
/*
Initialize
*/

var app_init, app_render, camera, container, cube, renderer, scene, stats;

scene = null;

camera = null;

renderer = null;

container = null;

cube = null;

stats = null;

app_init = function() {
  var geometry, material;
  container = $('#first')[0];
  $('#first').mousemove(function(ev) {
    cube.rotation.x += 0.2*(ev.clientX - window.innerWidth/2)/window.innerWidth;
    cube.rotation.y += 0.2*(ev.clientY - window.innerHeight/2)/window.innerHeight;
    return camera.lookAt(scene.position);
  });
  scene = new THREE.Scene;
  camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
  renderer = new THREE.WebGLRenderer;
  renderer.setSize(window.innerWidth, window.innerHeight);
  container.appendChild(renderer.domElement);
  geometry = new THREE.CubeGeometry(1, 1, 1);
  material = new THREE.MeshBasicMaterial({
    color: 0xff0000
  });
  cube = new THREE.Mesh(geometry, material);
  stats = new Stats;
  stats.domElement.style.position = 'absolute';
  stats.domElement.style.top = '0px';
  container.appendChild(stats.domElement);
  scene.add(cube);
  return camera.position.z = 5;
};

/*
Update
*/

app_render = function() {
  requestAnimationFrame(app_render);
  stats.update();
  return renderer.render(scene, camera);
};
