// Generated by CoffeeScript 1.4.0
(function() {
  var DualQuaternion;

  DualQuaternion = (function() {

    function DualQuaternion(quat, trans) {
      this.quat = quat;
      this.trans = trans;
    }

    return DualQuaternion;

  })();

}).call(this);
